apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop4
  template:
    metadata:
      labels:
        app: workshop4
    spec:
      containers:
        - args:
            - python
            - wsgi.py
            - runserver
            - 0.0.0.0:5000
          name: workshop4
          image: bhflaskregistry.azurecr.io/helloflask-azure:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "bhtravel-server.postgres.database.azure.com"
            - name: DATABASE_USER
              value: "formallizard4"
            - name: DATABASE_PASSWORD
              value: "ka5tZUd2x4uQaitGAE3trg"
            - name: DATABASE_NAME
              value: "hotel_trip_advisor"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "hotel_tripadvisor"
                    operator: In
                    values:
                      - workshop4
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: workshop4-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: workshop4
